/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ProtectedVerifyEmailRouteImport } from './routes/_protected/verify-email'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedCreatePostRouteImport } from './routes/_protected/create-post'
import { Route as GuestOnlyRegisterRouteImport } from './routes/_guest-only/register'
import { Route as GuestOnlyLoginRouteImport } from './routes/_guest-only/login'
import { Route as GuestOnlyForgotPasswordRouteImport } from './routes/_guest-only/forgot-password'
import { Route as ProtectedEditPostPostIdRouteImport } from './routes/_protected/edit-post/$postId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedVerifyEmailRoute = ProtectedVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreatePostRoute = ProtectedCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => ProtectedRoute,
} as any)
const GuestOnlyRegisterRoute = GuestOnlyRegisterRouteImport.update({
  id: '/_guest-only/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOnlyLoginRoute = GuestOnlyLoginRouteImport.update({
  id: '/_guest-only/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOnlyForgotPasswordRoute = GuestOnlyForgotPasswordRouteImport.update({
  id: '/_guest-only/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedEditPostPostIdRoute = ProtectedEditPostPostIdRouteImport.update({
  id: '/edit-post/$postId',
  path: '/edit-post/$postId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/locations': typeof LocationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof GuestOnlyForgotPasswordRoute
  '/login': typeof GuestOnlyLoginRoute
  '/register': typeof GuestOnlyRegisterRoute
  '/create-post': typeof ProtectedCreatePostRoute
  '/profile': typeof ProtectedProfileRoute
  '/verify-email': typeof ProtectedVerifyEmailRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/edit-post/$postId': typeof ProtectedEditPostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/locations': typeof LocationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof GuestOnlyForgotPasswordRoute
  '/login': typeof GuestOnlyLoginRoute
  '/register': typeof GuestOnlyRegisterRoute
  '/create-post': typeof ProtectedCreatePostRoute
  '/profile': typeof ProtectedProfileRoute
  '/verify-email': typeof ProtectedVerifyEmailRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/edit-post/$postId': typeof ProtectedEditPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/locations': typeof LocationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_guest-only/forgot-password': typeof GuestOnlyForgotPasswordRoute
  '/_guest-only/login': typeof GuestOnlyLoginRoute
  '/_guest-only/register': typeof GuestOnlyRegisterRoute
  '/_protected/create-post': typeof ProtectedCreatePostRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/verify-email': typeof ProtectedVerifyEmailRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/_protected/edit-post/$postId': typeof ProtectedEditPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/locations'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-post'
    | '/profile'
    | '/verify-email'
    | '/users/$userId'
    | '/edit-post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/locations'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-post'
    | '/profile'
    | '/verify-email'
    | '/users/$userId'
    | '/edit-post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_protected'
    | '/confirm-email'
    | '/locations'
    | '/reset-password'
    | '/_guest-only/forgot-password'
    | '/_guest-only/login'
    | '/_guest-only/register'
    | '/_protected/create-post'
    | '/_protected/profile'
    | '/_protected/verify-email'
    | '/users/$userId'
    | '/_protected/edit-post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  LocationsRoute: typeof LocationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  GuestOnlyForgotPasswordRoute: typeof GuestOnlyForgotPasswordRoute
  GuestOnlyLoginRoute: typeof GuestOnlyLoginRoute
  GuestOnlyRegisterRoute: typeof GuestOnlyRegisterRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/verify-email': {
      id: '/_protected/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof ProtectedVerifyEmailRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create-post': {
      id: '/_protected/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof ProtectedCreatePostRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_guest-only/register': {
      id: '/_guest-only/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestOnlyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest-only/login': {
      id: '/_guest-only/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestOnlyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest-only/forgot-password': {
      id: '/_guest-only/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestOnlyForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/edit-post/$postId': {
      id: '/_protected/edit-post/$postId'
      path: '/edit-post/$postId'
      fullPath: '/edit-post/$postId'
      preLoaderRoute: typeof ProtectedEditPostPostIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedCreatePostRoute: typeof ProtectedCreatePostRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedVerifyEmailRoute: typeof ProtectedVerifyEmailRoute
  ProtectedEditPostPostIdRoute: typeof ProtectedEditPostPostIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCreatePostRoute: ProtectedCreatePostRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedVerifyEmailRoute: ProtectedVerifyEmailRoute,
  ProtectedEditPostPostIdRoute: ProtectedEditPostPostIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  LocationsRoute: LocationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  GuestOnlyForgotPasswordRoute: GuestOnlyForgotPasswordRoute,
  GuestOnlyLoginRoute: GuestOnlyLoginRoute,
  GuestOnlyRegisterRoute: GuestOnlyRegisterRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
